version: "3.8"

services:
  haul-road-detection-2:
    build:
      context: ..
      dockerfile: Dockerfile 
    volumes:
      - "../src:/code/src"  # Mount source code directory.
      - "../requirements.txt:/code/requirements.txt"  # Mount requirements file.
      - "D:/Mines/CIL/Dipka OCP (SECL)/DPK_Full_Lease_Area_Survey/dtm.tif:/code/files/inputs/dtm.tif"  # Mount DTM file.
      - "D:/Mines/CIL/Dipka OCP (SECL)/DPK_Full_Lease_Area_Survey/smartlines/:/code/files/inputs/shapefiles"  # Comment if no input shapefiles are needed.
      - "${OUTPUT_DIR:-D:/Susanket/Haul_Road_Detection/docker-compose-outputs/cil/hra/dipka/dipka-run3-chunk200-smooth150-meddist10-area15-polyintbased}:/code/files/outputs"  # Mount output folder path. Directory will be created if it doesn't exist.
      - "./temp/smartline_workflow:/code/files/temp"  # Temporary cache directory.
    command: ["python3", "-m", "src.main"]
    environment:
      # Required Inputs.
      DEBUG: "true"
      ENVIRONMENT: "platform"
      WORKFLOW: "hrd_from_smart_line"

      # Paths.
      TEMPORARY_CACHE_DIRECTORY: "/code/files/temp"
      INPUT_DTM_PATH: "/code/files/inputs/dtm.tif"
      OUTPUT_FOLDER_PATH: "/code/files/outputs"

      # Algorithm Specific Inputs.
      # Haul Road Analysis Inputs.
      INPUT_LINESTRING_SHAPEFILE_PATH: "/code/files/inputs/shapefiles/smartline3.shp"
      INPUT_MEDIAN_SHAPEFILE_PATH: "/code/files/inputs/shapefiles/median.shp"
      CHAINAGE_DISTANCE: "10"
      VEHICLE_WIDTH: "7"

      # Drainage Analysis Inputs.
      AREA_ACCUMULATION: "${AREA_ACCUMULATION:-900}"

    stdin_open: true
    tty: true


  bench_crest_toe_detection:
    build:
      context: ../
      dockerfile: Dockerfile
    volumes:
      - "../src:/code/src"
      - "../requirements.txt:/code/requirements.txt" # Mount requirements file.
      - "D:/Mines/TSL/West Bokaro/Query SEB/dtm.tif:/code/files/inputs/dtm.tif"
      - "D:/OUTPUT_HRA/docker-compose-outputs/tsl/bctd/West Bokaro - QSEB:/code/files/outputs"
      - "./temp/workflow:/code/files/temp"
    command: [ "python3", "-m", "src.main" ]
    environment:
      # Required Inputs.
      - DEBUG=true
      - ENVIRONMENT=platform
      - WORKFLOW=bench_crest_toe_detection

      # Paths.
      - TEMPORARY_CACHE_DIRECTORY=/code/files/temp
      - INPUT_DTM_PATH=/code/files/inputs/dtm.tif
      # - INPUT_AOI_SHAPEFILE_PATH=/code/files/outputs/aoi.shp
      - OUTPUT_FOLDER_PATH=/code/files/outputs

    stdin_open: true
    tty: true